###################################
#            EpicMail             #
#     A powered mail system       #
#         plugin config           #
###################################

# The data save type, default is SQLITE
# Available options: MYSQL, SQLITE
storageType: SQLITE

# Plugin language, default is zh-CN (Chinese)
# Available options: check the /EpicMail/language/ folder
language: zh-CN

mailOption:
  # Automatically newline when the length of the message exceeds this value
  messageNewline: 16
